### ISSUE TITLE
[question] optiga_crypt_tls_prf_sha256 example

### ISSUE THREAD

**Issue by ozanoner** [Infineon/optiga-trust-x#11]
Hi @ayushev ,
I tried the example [here](https://github.com/Infineon/optiga-trust-x/wiki/Trust-X-Crypt-API#optiga_crypt_tls_prf_sha256) for optiga_crypt_tls_prf_sha256 as you suggested before. In this example, there is a check like
```
if ((coprocessor_uid[26] < 11) || (coprocessor_uid[27] < 18))  // ??
        {
        	/* This example can't work with this firmware, you need
        	 * to populate and use session OID instead
        	 */
        	return_status = OPTIGA_LIB_SUCCESS;
        	break;
        }
```
I couldn't understand that condition exactly. My test fails at that point. In the solution reference manual (v1.35) there is no information about those bytes. But the closest index (25) contains ESW build number (page 88).

My module has the following values in this array (`coprocessor_uid`)
idx  |  val
25   |  0x10
26   |  0x48
27   |  0x00

I appreciate if you have any suggestion.
Kind regards

**Comment by ayushev** [comment]
this Coprocessor UID contains last two bytes of the firmware build version (in your case 1.20.**1048**).
For this firmware you can't generate the PRF using the arbitrary data object (the 0xF1D0 is one of them),
for this you need to use one of session contexts (0xE100, 0xE101, 0xE102, 0xE103) instead.
I have updated the Wiki page accordingly: https://github.com/Infineon/optiga-trust-x/wiki/Trust-X-Crypt-API#optiga_crypt_tls_prf_sha256
If you still need to use PRF out of the Arbitrary Data Object (the difference with Session Context is that in the latter you can't user defined data and data can't be stored there permanently, after a reset it will disappear), please contact your Infineon partner and refer to my name, she or he can find me internally. We can find you another sample.

**Comment by ozanoner** [comment]
Thank you!
