### ISSUE TITLE
[documentation] optiga_crypt_ecdsa_sign

### ISSUE THREAD

**Issue by ozanoner** [Infineon/optiga-trust-x#15]
Kindly reminder: The function has 5 parameters as documented, but 6 provided in the example below the function description.

https://github.com/Infineon/optiga-trust-x/wiki/Trust-X-Crypt-API#optiga_crypt_ecdsa_sign

**Comment by ayushev** [comment]
Hmm, I haven't seen the original email.
Thank you for the hint, indeed, the example is incorrect
[Fixed](https://github.com/Infineon/optiga-trust-x/wiki/Trust-X-Crypt-API/acaf67c7dfa25d0311354897cf03080f409dc0ad) now
