### ISSUE TITLE
Branch tag v1.0.2, Inconsistent case file naming creates build error in Linux platform.

### ISSUE THREAD

**Issue by timothyyong** [Infineon/optiga-trust-x#2]
Found inconsistent case file naming when building the code in Linux. Following is the changes I made to get it to build correctly. using branch tag v1.0.2

a.       optiga/dtls/OCPConfig.c:34:41  
“optiga/dtls/DtlsRecordlayer.h” change to  “optiga/dtls/DtlsRecordLayer.h”

b.       optiga/dtls/DtlsFlightHandler.c:33:43  
“optiga/dtls/DtlsFlighthandler.h” change to “optiga/dtls/DtlsFlightHandler.h”

c.       Rename  “optiga/include/optiga/dtls/DtlsFlighthandler.h” to DtlsFlightHandler.h

**Comment by ayushev** [comment]
optiga/dtls/DtlsFlighthandler.h file is a part of the core library, it can't be changed
