### ISSUE TITLE
Signature verification fails

### ISSUE THREAD

**Issue by dogusriddle** [Infineon/optiga-trust-x#24]
Hello, when I try to verify a signature I signed with the keys inside the device, it either returns error code **0x01 | Invalid OID** or **0x05 | Invalid parameter in command data field**. I am going to post my program logic, maybe you can see and tell me if there is a flaw.

1. Init the device succesfully.
2. Generate a keypair at OPTIGA_KEY_STORE_ID_E0F1
3. Save the pubkey in 0xF1DC
4. Read the pubkey at 0xF1DC
5. Hash a "Hello World!" string
6. Sign the string with the key at OPTIGA_KEY_STORE_ID_E0F1

Signature looks like this :
`02-21-00-da-0b-64-31-f0-f1-9e-49-d4-dc-6f-14-a1-00-14-dc-00-33-05-4a-84-5c-45-d4-21-f9-5d-e1-c9-05-35-43-02-20-4d-80-63-52-c9-11-79-37-d0-cf-ec-ec-32-f6-c9-51-77-9a-50-a7-6c-06-c0-16-e3-dc-77-4d-69-1b-30-a5`

So far all operations return OPTIGA_LIB_SUCCESS and I can see that I can read the same public key from the GP storage on each different run. The signature of the same hash with the same key changes every time tho. But I believe this is expected. When I try to do verification in the following ways it fails

````

`SE_STATUS` v3_verify(const uint8_t *pKeyData, uint16_t keyDataLen, const uint8_t *pHash, uint16_t hashLen, const uint8_t *pSignature, uint16_t signatureLen)
									
{
    optiga_key_id_t oid = OPTIGA_KEY_STORE_ID_E0F1;
    optiga_lib_status_t return_status = OPTIGA_LIB_ERROR;




    do
    {

        return_status = optiga_crypt_ecdsa_verify (pHash,
                                                   hashLen,
                                                   pSignature,
                                                   signatureLen,
				       	   // OPTIGA_CRYPT_OID_DATA stands for OID in the public_key_details
		                                   OPTIGA_CRYPT_OID_DATA,
                                                   &oid);

        if(return_status != OPTIGA_LIB_SUCCESS)
        {
			//Signature verification failed.
            printf("%02x\n",return_status);
            break;
        }

    } while(FALSE);

    return return_status;
}`
````

This returns Invalid OID error. If I provide the function the saved public key which is also stored inside the device.

````
`SE_STATUS` v3_verify_external(const uint8_t *pKeyData, uint16_t keyDataLen, const uint8_t *pHash, uint16_t hashLen, const uint8_t *pSignature, uint16_t signatureLen)
									
{
	public_key_from_host_t public_key_details = {
                                                 pKeyData,
                                                 keyDataLen,
		                                 OPTIGA_ECC_NIST_P_256
                                                };


    optiga_lib_status_t return_status = OPTIGA_LIB_ERROR;




    do
    {

        return_status = optiga_crypt_ecdsa_verify (pHash,
                                                   hashLen,
                                                   pSignature,
                                                   signatureLe
// OPTIGA_CRYPT_OID_DATA stands for OID in the public_key_details
					           OPTIGA_CRYPT_HOST_DATA,					
                                                   &public_key_details);

        if(return_status != OPTIGA_LIB_SUCCESS)
        {
			//Signature verification failed.
            printf("%d\n",return_status);
            break;
        }

    } while(FALSE);

    return return_status;
}`
````

This returns Invalid parameter in command data field. Is there any chance I am making a mistake when using these functions ?

**Comment by pwiegele** [comment]
Lets break it into more steps. Try the following:
1. Have a look at this example [here](https://github.com/Infineon/optiga-trust-x/blob/master/examples/authenticate_chip/example_authenticate_chip.c)
2. If you want to use public key from the device you need to store them here
3. Inspect the raw data of the public key that you generate, does it start with a 0x04?

**Comment by dogusriddle** [comment]
my pub key is : 03-42-00-04-dc-8e-c5-a9-54-43-21-c1-50-22-31-69-48-11-8b-a8-15-32-fa-b6-30-c3-6c-55-a4-7e-57-29-2c-09-4b-02-f8-d3-83-4a-f7-77-5b-14-ff-8f-11-dd-22-61-09-2e-08-53-d6-0e-94-96-95-46-e8-3a-49-4d-92-c0-b3-75

I am generating my key pairs like this , so I believe they are already stored in the device. 

`
optiga_key_id = index + OPTIGA_KEY_STORE_ID_E0F0;

optiga_crypt_ecc_generate_keypair(OPTIGA_ECC_NIST_P_256,
                                                          (uint8_t)OPTIGA_KEY_USAGE_SIGN,
                                                          FALSE,
							  &optiga_key_id,
                                                          public_key,
                                                          &public_key_length);`

**Comment by pwiegele** [comment]
Try to strip away the first three bytes, does it change anything?

**Comment by dogusriddle** [comment]
It still fails, funny thing is I can run this example just fine, with the pre-signed digest. 
[verify example](https://github.com/Infineon/optiga-trust-x/blob/474a8213c3399e1ed76e7b22c8370298e02c4f73/examples/optiga/example_optiga_crypt_ecdsa_verify.c)

**Comment by pwiegele** [comment]
I had a look at your first post. Looks like you are using the wrong oid to verify signature. You have to use the public key stored at 0xF1DC instead of using the private key at 0xE0F1. Correct me if I am wrong.

**Comment by dogusriddle** [comment]
Valid point but how do you know public key one has the address of 0xF1DC ? It shows as GP memory in the wiki. And in the v3_verify_external function above, I inject the pubkey from outside but it gives me :

Invalid parameter in data field | 0x05 | Invalid parameter in command data field

**Comment by pwiegele** [comment]
I am not sure why the verify with an external is not working as expected. Can you try to wrap your public key into a certificate and store it at 0xE0E8? Then run the verify again referencing the key mentioned before?

**Comment by dogusriddle** [comment]
I fixed the external verification somehow :) But the verification with the public keys stored inside still doesnt work. It gives me 80001001 error which means invalid OID. What OID should I use for each public key slots ?

**Comment by pwiegele** [comment]
Good to hear! You can use the slot 0xE0E8 to store the public key, but it has to be inside of a x509 certificate. OPTIGA Trust X will internally parse the certificate and extract the public key which will be used during the verify command.

**Comment by dogusriddle** [comment]
Thanks a bunch, do you have any documents that shows the assembly of the certificate with the stored public key ? Other than this all my questions have been answered thank you.

**Comment by pwiegele** [comment]
Happy to hear it works for you.
What you need to do is:
1. Generate a new keypair 
2. Generate a csr with the public key 
3. Generate a self signed CA
4. CA needs to sign the csr 

You can find more details [here](https://github.com/Infineon/personalize-optiga-trust/tree/master/using-self-signed-ca)

If you run into troubles create an issue and we will take it from there.
