### ISSUE TITLE
Storing data on the GP memory

### ISSUE THREAD

**Issue by dogusriddle** [Infineon/optiga-trust-x#26]
Hello , I am trying to use the chip for secure data storage but writing to some OIDs directly doesn't 

work as expected. I can write & read what I wrote to memory regions between F1D0- F1DF by 

using _optiga_util_write_data_ and _optiga_util_read_data_. Although the functions return 

_OPTIGA_LIB_SUCCESS_ , I cant seem to read what I wrote to OIDS F1E0, F1E2 and E0E8. I 

believe I will have to set up the meta data for these regions before I can put my persistent data

 there. The page under the wiki didn't really help me much . How can I set the OIDS so that I can 

write & read to them and the data stays there until I overwrite and can be modified anytime ?

**Comment by dogusriddle** [comment]
I have been reading the Wiki and the solution reference manual since yesterday evening and honestly I have no idea how to set the GP memory for simple read / write operations. Can you please help me ?

**Comment by pwiegele** [comment]
F1E0 and E0E8 are working on my end. F1E2 is not a valid object ID.
Seems like the your problem is solved?

**Comment by dogusriddle** [comment]
Yes I figured F1E2 wouldnt be a valid location to write, can you show me where it is mentioned that that object is not valid ? Because on the wiki it says General  Purpose Data 2.

**Comment by pwiegele** [comment]
Your are right there is a mistake. (see [here](https://github.com/Infineon/optiga-trust-x/issues/27))
