### ISSUE TITLE
On chip encryption - Trust X SLS 32AIA

### ISSUE THREAD

**Issue by san-sei** [Infineon/optiga-trust-x#29]
How can we rely on Trust X to simply encrypt / decrypt data on chip? What I expect is the ability to create a symmetric key there on chip and retrieve a 'optiga_key_id_t' reference relatively,  so I can use this symmetric key to provide maximum protection by doing encryption before storing the data on the main SoC flash storage.

**Comment by san-sei** [comment]
I don't want the symmetric key to be exportable. That means I want to ask optiga to do encryption / decryption. 
Any suggestion or alternatives would be appreciated.

**Comment by ayushev** [comment]
I think this issue duplicates #28
