### ISSUE TITLE
OPTIGA-Crypt-API wiki document error for API optiga_crypt_ecc_generate_keypair

### ISSUE THREAD

**Issue by timothyyong** [Infineon/optiga-trust-x#3]
In the wiki link the API optiga_crypt_ecc_generate_keypair() doc show only 5 parameters but the example code shows 6. The 3rd parameter (just after the key usage) is missing in the doc.
below shows the example code.

        return_status = optiga_crypt_ecc_generate_keypair(OPTIGA_ECC_NIST_P_256,
                                                          (uint8_t)OPTIGA_KEY_USAGE_SIGN,
                                                          FALSE,
                                                          &optiga_key_id,
                                                          public_key,
                                                          &public_key_length);

**Comment by ayushev** [comment]
Fixed
