### ISSUE TITLE
Multiple definition of mbedtls_hardware_poll()

### ISSUE THREAD

**Issue by panmasuo** [Infineon/optiga-trust-x#32]
Hi,
I was going through some code involving mbedTLS external library and i had a problem with multiple definition of *mbedtls_hardware_poll()* function. 
I noticed there is a file [enrtopy_optiga.c](https://github.com/Infineon/optiga-trust-x/blob/master/externals/mbedtls-2.12.0/enrtopy_optiga.c) (with a typo in a name) and [trustx_random.c](https://github.com/Infineon/optiga-trust-x/blob/master/examples/mbedtls_port/trustx_random.c) both checking for **MBEDTLS_ENTROPY_HARDWARE_ALT** and defining *mbedtls_hardware_poll()* function. 

Is that a bug?

**Comment by ayushev** [comment]
Thanks @panmasuo , fixed in 5e0e029 and in a610c5a
