### ISSUE TITLE
I2C write bug

### ISSUE THREAD

**Issue by krajcark** [Infineon/optiga-trust-x#37]
Hi,
When I2C write fails, its sets the status to PAL_STATUS_I2C_BUSY, should it not be set to PAL_STATUS_FAILURE?

https://github.com/Infineon/optiga-trust-x/blob/7376f458336f25abb477b27eb96edefe2d671270/pal/mbedos/pal_i2c.cpp#L262

**Comment by pwiegele** [comment]
You are right @krajcark I fixed it here [here](https://github.com/Infineon/optiga-trust-x/commit/6342c317b31e55f50bfa9598b703878cb348d60d)
