### ISSUE TITLE
Mbed OS PAL outdated

### ISSUE THREAD

**Issue by boraozgen** [Infineon/optiga-trust-x#38]
Hello @ayushev,

we are using the library together with Mbed OS. We noticed some problems with the provided PAL, such as #37, or the fact that the reset function is not implemented. Furthermore, Mbed OS 6 deprecates some API used in the PAL, such as wait_ms(). We have now a working PAL which is Mbed OS 6 compatible. Are you open for PRs in this area?

**Comment by ayushev** [comment]
@boraozgen You are right, the reference implementaiton was based on a different Mbed OS version. All contributions a warmly welcome!
If you also do have a working reference implemention, we can refer to it in the mbedOS PAL section, if you like.

**Comment by ayushev** [comment]
Hello @boraozgen do you still plan to commit a PR?
